spring.application.name=weather_app
weather.api.key=0dfabee2cbca43ef83665423260903
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forcast.url=http://api.weatherapi.com/v1/forecast.json
